version: '3'
services:
  web:
    container_name: sanic-test
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 5000:5000
    volumes:
      - .:/app
    command: python3 run.py
volumes:
  data-volume:
